# vim:ft=yaml
version: "3.3"
services:
  moarcats:
    image: moarcats
    build:
      context: .
    container_name: moarcats
    ports:
      - 127.0.0.1:9840:8080
    volumes:
      - ./cats:/cats:ro
    links:
      - redis
    environment:
      - RACK_ENV
      - SOURCE_COMMIT
      - REDIS_URL=redis://redis:6379/0
  redis:
    image: redis:3.2-alpine
    container_name: moarcats_redis
    volumes:
      - moarcats-redis-data:/data
    command: redis-server --appendonly yes

volumes:
  moarcats-redis-data:
