name: CI/CD

on:
  push:
    branches:
      - master
  schedule:
    - cron: '47 * * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login to registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u ${{ github.actor }} --password-stdin docker.pkg.github.com
      - uses: actions/checkout@v2
      - name: Build image
        run: |
          docker build -t docker.pkg.github.com/flores/moarcats/app:$(echo $GITHUB_SHA | head -c7) .
          docker tag docker.pkg.github.com/flores/moarcats/app:$(echo $GITHUB_SHA | head -c7) docker.pkg.github.com/flores/moarcats/app:latest
      - name: Publish image
        run: |
          docker push docker.pkg.github.com/flores/moarcats/app
